### Crear un comentario
POST http://localhost:8080/api/v1/comentario/crear
Content-Type: application/json
Accept: application/json

{
    "recetaID": 1,
    "userID": 1,
    "textoComentario": "Este es un comentario de ejemplo."
}

### Obtener un comentario por ID
GET http://localhost:8080/api/v1/comentario/1
Accept: application/json

### Listar todos los comentarios
GET http://localhost:8080/api/v1/comentario/listar
Accept: application/json

### Actualizar un comentario por ID
PUT http://localhost:8080/api/v1/comentario/1
Content-Type: application/json
Accept: application/json

{
    "recetaID": 1,
    "userID": 1,
    "textoComentario": "Este es un comentario actualizado."
}

### Eliminar un comentario por ID
DELETE http://localhost:8080/api/v1/comentario/1
Accept: application/json
