###aszd
POST http://localhost:8080/api/v1/usuario/register
Content-Type: application/json
Accept: application/json

{
    "nombre": "NombreEjemplo",
    "apellido": "ApellidoEjemplo",
    "nombreusuario": "UsuarioEjemplo",
    "correo": "correo@example.com",
    "fotoperfil": null
}

###Obetener todas los usuarios
GET http://localhost:8080/api/v1/usuario